blank_issues_enabled: false
contact_links:
  - name: AxT 主群
    url: https://qm.qq.com/cgi-bin/qm/qr?k=4xIoOBlunlOqYDjl7l0hjgyT8_Wj_TXZ&jump_from=webapi&authKey=wtdZn5mWnX2B0wcQriPt42yaVzmXoTPQcIBjB8pXV9D+68u9Auv7U0pqZNMqmlR5
    about: AxTBot的核心开发成员在这哦~
  - name: 在 Linear 上反馈
    url: https://linear.app/axtbot/team/ATB/overview
    about: 在Linear上也行，平时都在这里看~
