from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path


BOT_TEMPLATE = '''"""
AxTBot launcher

Run with: python bot.py
"""
from __future__ import annotations

from app.main import app

if __name__ == "__main__":
    import uvicorn
    from app.modules import config_loader
    from app.service import certificate_service

    config_loader.load("local.env")
    certificate_service.refresh()
    core_config = config_loader.get_core_config()
    kwargs = {
        "host": core_config.host,
        "port": core_config.port,
        "reload": bool(core_config.reload_on_change),
        "log_level": core_config.log_level.lower(),
        "log_config": None,
    }
    kwargs.update(certificate_service.get_uvicorn_kwargs())
    uvicorn.run("app.main:app", **kwargs)
'''


def _find_project_root(start: Path | None = None) -> Path:
    current = (start or Path.cwd()).resolve()
    for candidate in [current, *current.parents]:
        if (candidate / "app").is_dir() and (candidate / "local.env").exists():
            return candidate
    return current


def _find_venv_python(project_root: Path) -> Path:
    venv_dir = project_root / ".venv"
    if os.name == "nt":
        candidates = [
            venv_dir / "Scripts" / "python.exe",
            venv_dir / "Scripts" / "python",
        ]
    else:
        candidates = [
            venv_dir / "bin" / "python",
            venv_dir / "bin" / "python3",
        ]

    for candidate in candidates:
        if candidate.exists():
            return candidate
    return Path(sys.executable)


def _ensure_bot_file(project_root: Path) -> Path:
    bot_path = project_root / "bot.py"
    if not bot_path.exists():
        bot_path.write_text(BOT_TEMPLATE, encoding="utf-8")
    return bot_path


def _ensure_project_skeleton(project_root: Path, overwrite: bool = False) -> None:
    app_dir = project_root / "app"
    data_dir = project_root / "data"
    plugins_dir = project_root / "plugins"

    app_dir.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)
    plugins_dir.mkdir(parents=True, exist_ok=True)

    for package_dir in [app_dir, app_dir / "router", app_dir / "router" / "api", app_dir / "router" / "hooks", app_dir / "service"]:
        package_dir.mkdir(parents=True, exist_ok=True)
        init_file = package_dir / "__init__.py"
        if overwrite or not init_file.exists():
            init_file.touch()

    bot_path = project_root / "bot.py"
    if overwrite or not bot_path.exists():
        bot_path.write_text(BOT_TEMPLATE, encoding="utf-8")

    readme_path = project_root / "README.md"
    if overwrite or not readme_path.exists():
        readme_path.write_text("# AxTBot\n\nGenerated by `axtbot init`.\n", encoding="utf-8")


def _resolve_port(value: str | int | None, fallback: int) -> int:
    if value is None:
        return fallback
    return int(value)


def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value or default


def _ask_yes_no(prompt: str, default: bool = True) -> bool:
    choice = "Y/n" if default else "y/N"
    value = input(f"{prompt} ({choice}): ").strip().lower()
    if not value:
        return default
    return value in {"y", "yes", "true", "1"}


def cmd_run(args: argparse.Namespace) -> int:
    project_root = _find_project_root()
    bot_path = _ensure_bot_file(project_root)
    python_executable = _find_venv_python(project_root)
    if python_executable == Path(sys.executable) and not (project_root / ".venv").exists():
        print("提示：当前目录没有找到 `.venv`，将使用当前 Python 运行。")
        print("如果你想优先使用项目环境，请先创建 `.venv`。")

    env_loader = project_root / "local.env"
    if env_loader.exists():
        with env_loader.open("r", encoding="utf-8") as handle:
            for line in handle:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                key, value = line.split("=", 1)
                key = key.strip()
                value = value.strip().strip('"').strip("'")
                if key == "FRAMEWORK_HOST" and args.host is None:
                    os.environ["FRAMEWORK_HOST"] = value
                elif key == "FRAMEWORK_PORT" and args.port is None:
                    os.environ["FRAMEWORK_PORT"] = value

    env = os.environ.copy()
    env["PYTHONPATH"] = str(project_root) + (
        os.pathsep + env["PYTHONPATH"] if env.get("PYTHONPATH") else ""
    )
    if args.host is not None:
        env["FRAMEWORK_HOST"] = str(args.host)
    if args.port is not None:
        env["FRAMEWORK_PORT"] = str(args.port)

    command = [str(python_executable), str(bot_path)]
    if args.dry_run:
        print(" ".join(command))
        return 0

    try:
        process = subprocess.Popen(command, cwd=str(project_root), env=env)
        return process.wait()
    except KeyboardInterrupt:
        if "process" in locals() and process.poll() is None:
            process.terminate()
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                process.kill()
        return 130


def cmd_init(args: argparse.Namespace) -> int:
    project_root = Path.cwd().resolve()
    project_name = args.name or _ask("Project name", project_root.name)
    overwrite = bool(args.force) if args.force is not None else _ask_yes_no("Overwrite existing files?", False)
    if not args.quiet:
        print(f"Creating AxTBot project: {project_name}")
        print(f"Location: {project_root}")
    _ensure_project_skeleton(project_root, overwrite=overwrite)
    local_env = project_root / "local.env"
    if overwrite or not local_env.exists():
        local_env.write_text(
            "\n".join(
                [
                    f'FRAMEWORK_PROJECT_NAME="{project_name}"',
                    'FRAMEWORK_HOST="0.0.0.0"',
                    "FRAMEWORK_PORT=8000",
                ]
            )
            + "\n",
            encoding="utf-8",
        )
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="axtbot", description="AxTBot CLI")
    subparsers = parser.add_subparsers(dest="command", required=True)

    run_parser = subparsers.add_parser("run", help="Run AxTBot in the current project")
    run_parser.add_argument("--dry-run", action="store_true", help="Print the command without running it")
    run_parser.add_argument("--host", default=None, help="Override FRAMEWORK_HOST")
    run_parser.add_argument("--port", default=None, help="Override FRAMEWORK_PORT")
    run_parser.set_defaults(func=cmd_run)

    init_parser = subparsers.add_parser("init", help="Create an AxTBot project skeleton")
    init_parser.add_argument("--name", default=None, help="Project name")
    init_parser.add_argument("--force", action="store_true", default=None, help="Overwrite existing files")
    init_parser.add_argument("--quiet", action="store_true", help="Reduce prompts and output")
    init_parser.set_defaults(func=cmd_init)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)
